"""add owner_user_id to availability_schedules

Revision ID: 7f358958e512
Revises: 8a0013ad3100
Create Date: 2026-05-01 12:48:27.774921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f358958e512'
down_revision: Union[str, Sequence[str], None] = '8a0013ad3100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # No production data yet — wipe schedules and everything that references them
    # so the new NOT NULL owner_user_id column can be added cleanly.
    op.execute("TRUNCATE availability_schedules CASCADE")

    op.add_column('availability_schedules', sa.Column('owner_user_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_availability_schedules_owner_user_id'), 'availability_schedules', ['owner_user_id'], unique=False)
    op.create_foreign_key(None, 'availability_schedules', 'users', ['owner_user_id'], ['id'], ondelete='CASCADE')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'availability_schedules', type_='foreignkey')
    op.drop_index(op.f('ix_availability_schedules_owner_user_id'), table_name='availability_schedules')
    op.drop_column('availability_schedules', 'owner_user_id')
    # ### end Alembic commands ###
