"""cascade FKs and unique constraints

Revision ID: 8a0013ad3100
Revises: eaaafd6faf19
Create Date: 2026-05-01 11:59:08.292588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a0013ad3100'
down_revision: Union[str, Sequence[str], None] = 'eaaafd6faf19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('certifications_crew_member_id_fkey'), 'certifications', type_='foreignkey')
    op.create_foreign_key(None, 'certifications', 'crew_members', ['crew_member_id'], ['user_id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_conversations_owner_crew', 'conversations', ['owner_id', 'crew_member_id'])
    op.drop_constraint(op.f('conversations_crew_member_id_fkey'), 'conversations', type_='foreignkey')
    op.drop_constraint(op.f('conversations_owner_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'crew_members', ['crew_member_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'conversations', 'yacht_owners', ['owner_id'], ['user_id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_crew_inquiries_owner_listing', 'crew_inquiries', ['owner_id', 'crew_listing_id'])
    op.drop_constraint(op.f('crew_inquiries_owner_id_fkey'), 'crew_inquiries', type_='foreignkey')
    op.drop_constraint(op.f('crew_inquiries_crew_listing_id_fkey'), 'crew_inquiries', type_='foreignkey')
    op.create_foreign_key(None, 'crew_inquiries', 'yacht_owners', ['owner_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'crew_inquiries', 'crew_listings', ['crew_listing_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('crew_listings_crew_member_id_fkey'), 'crew_listings', type_='foreignkey')
    op.create_foreign_key(None, 'crew_listings', 'crew_members', ['crew_member_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('crew_members_user_id_fkey'), 'crew_members', type_='foreignkey')
    op.create_foreign_key(None, 'crew_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_job_applications_crew_posting', 'job_applications', ['crewmember_id', 'jobposting_id'])
    op.drop_constraint(op.f('job_applications_jobposting_id_fkey'), 'job_applications', type_='foreignkey')
    op.drop_constraint(op.f('job_applications_crewmember_id_fkey'), 'job_applications', type_='foreignkey')
    op.create_foreign_key(None, 'job_applications', 'job_postings', ['jobposting_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'job_applications', 'crew_members', ['crewmember_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('job_posting_media_jobposting_id_fkey'), 'job_posting_media', type_='foreignkey')
    op.create_foreign_key(None, 'job_posting_media', 'job_postings', ['jobposting_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('job_postings_owner_id_fkey'), 'job_postings', type_='foreignkey')
    op.create_foreign_key(None, 'job_postings', 'yacht_owners', ['owner_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('messages_conversation_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('yacht_owners_user_id_fkey'), 'yacht_owners', type_='foreignkey')
    op.create_foreign_key(None, 'yacht_owners', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'yacht_owners', type_='foreignkey')
    op.create_foreign_key(op.f('yacht_owners_user_id_fkey'), 'yacht_owners', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(op.f('messages_conversation_id_fkey'), 'messages', 'conversations', ['conversation_id'], ['id'])
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.create_foreign_key(op.f('job_postings_owner_id_fkey'), 'job_postings', 'yacht_owners', ['owner_id'], ['user_id'])
    op.drop_constraint(None, 'job_posting_media', type_='foreignkey')
    op.create_foreign_key(op.f('job_posting_media_jobposting_id_fkey'), 'job_posting_media', 'job_postings', ['jobposting_id'], ['id'])
    op.drop_constraint(None, 'job_applications', type_='foreignkey')
    op.drop_constraint(None, 'job_applications', type_='foreignkey')
    op.create_foreign_key(op.f('job_applications_crewmember_id_fkey'), 'job_applications', 'crew_members', ['crewmember_id'], ['user_id'])
    op.create_foreign_key(op.f('job_applications_jobposting_id_fkey'), 'job_applications', 'job_postings', ['jobposting_id'], ['id'])
    op.drop_constraint('uq_job_applications_crew_posting', 'job_applications', type_='unique')
    op.drop_constraint(None, 'crew_members', type_='foreignkey')
    op.create_foreign_key(op.f('crew_members_user_id_fkey'), 'crew_members', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'crew_listings', type_='foreignkey')
    op.create_foreign_key(op.f('crew_listings_crew_member_id_fkey'), 'crew_listings', 'crew_members', ['crew_member_id'], ['user_id'])
    op.drop_constraint(None, 'crew_inquiries', type_='foreignkey')
    op.drop_constraint(None, 'crew_inquiries', type_='foreignkey')
    op.create_foreign_key(op.f('crew_inquiries_crew_listing_id_fkey'), 'crew_inquiries', 'crew_listings', ['crew_listing_id'], ['id'])
    op.create_foreign_key(op.f('crew_inquiries_owner_id_fkey'), 'crew_inquiries', 'yacht_owners', ['owner_id'], ['user_id'])
    op.drop_constraint('uq_crew_inquiries_owner_listing', 'crew_inquiries', type_='unique')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_owner_id_fkey'), 'conversations', 'yacht_owners', ['owner_id'], ['user_id'])
    op.create_foreign_key(op.f('conversations_crew_member_id_fkey'), 'conversations', 'crew_members', ['crew_member_id'], ['user_id'])
    op.drop_constraint('uq_conversations_owner_crew', 'conversations', type_='unique')
    op.drop_constraint(None, 'certifications', type_='foreignkey')
    op.create_foreign_key(op.f('certifications_crew_member_id_fkey'), 'certifications', 'crew_members', ['crew_member_id'], ['user_id'])
    # ### end Alembic commands ###
